/* CONFIGURATION: replace both placeholders before collecting real pilot data. */
const GA_MEASUREMENT_ID='G-M8PC5KCVMF';
const SCRIPT_URL='https://script.google.com/macros/s/AKfycbwtw-RVVZibZj_3rGwPJoahtUhS4etzjdnKraWuZznTeeuNlezu78fwZKDl8vc8W59z6w/exec';
window.dataLayer=window.dataLayer||[];function gtag(){window.dataLayer.push(arguments)}
if(GA_MEASUREMENT_ID!=='G-M8PC5KCVMF'){const s=document.createElement('script');s.async=true;s.src=`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`;document.head.appendChild(s);gtag('js',new Date());gtag('config',GA_MEASUREMENT_ID)}
function gaEvent(name,params={}){if(GA_MEASUREMENT_ID!=='G-M8PC5KCVMF')gtag('event',name,params)}function trackOrderClick(source='unknown'){gaEvent('order_now_click',{source})}function trackFormStarted(){gaEvent('form_started',{form_name:'pilot_order'})}function trackFormSubmitted(){gaEvent('form_completed',{form_name:'pilot_order'})}function trackConfirmationViewed(){gaEvent('confirmation_viewed',{page:'confirmation'})}
const header=document.getElementById('site-header');if(header)window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>18),{passive:true});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.querySelectorAll('[data-track]').forEach(button=>button.addEventListener('click',()=>trackOrderClick(button.dataset.track)));
const depths=[25,50,75,100],trackedDepths=new Set;window.addEventListener('scroll',()=>{const height=document.documentElement.scrollHeight-window.innerHeight,progress=height?(window.scrollY/height)*100:100;depths.forEach(depth=>{if(progress>=depth&&!trackedDepths.has(depth)){trackedDepths.add(depth);gaEvent('scroll_depth',{percent_scrolled:depth})}})},{passive:true});
const form=document.getElementById('pilot-form');if(form){let formStarted=false;form.addEventListener('focusin',()=>{if(!formStarted){formStarted=true;trackFormStarted()}});form.addEventListener('submit',async event=>{event.preventDefault();const validationError=document.getElementById('form-error'),submitError=document.getElementById('submit-error');if(!form.checkValidity()){validationError.classList.remove('hidden');form.reportValidity();return}validationError.classList.add('hidden');submitError.classList.add('hidden');const submitButton=document.getElementById('submit-button'),label=submitButton.querySelector('.button-label'),loading=document.getElementById('loading-label');submitButton.disabled=true;label.classList.add('hidden');loading.classList.remove('hidden');loading.classList.add('flex');const data=Object.fromEntries(new FormData(form).entries()),payload={timestamp:new Date().toISOString(),fullName:data.fullName,university:data.university,residence:data.residence,phoneNumber:data.phone,email:data.email,medication:data.medication,address:data.address,preferredPharmacy:data.pharmacy||'',paymentMethod:data.payment,checkboxAccepted:data.feeAcknowledgement?'Yes':'No',browser:navigator.userAgent,submissionTime:new Date().toLocaleString()};try{if(SCRIPT_URL==='YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL'){await new Promise(resolve=>setTimeout(resolve,700))}else{const response=await fetch(SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});if(!response)throw new Error('No response')}trackFormSubmitted();window.location.href='confirmation.html'}catch(error){submitError.classList.remove('hidden');submitButton.disabled=false;label.classList.remove('hidden');loading.classList.add('hidden');loading.classList.remove('flex')}})}if(document.body.classList.contains('confirmation-bg'))trackConfirmationViewed();
